cinemahistory/apps/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('area/<area_name>/', views.area, name='area'),
    path('article/<int:article_id>/', views.detail, name='detail'),
    path('?search=<search_query>/', views.search, name='search'),
]

cinemahistory/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
    path('', include('articles.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cinemahistory/apps/articles/models.py
import datetime
from django.utils import timezone
from django.db import models

class Area(models.Model):
    area_name = models.CharField('name of area', max_length=100)
    area_name_ru = models.TextField('name of area (rus)', max_length=100)

    def __str__(self):
        return self.area_name

    #class Meta:
    #    verbouse_name = 'Часть света'
    #    verbouse_name_plural = 'Части света'

class Article(models.Model):
    article_title = models.CharField('article title', max_length=200)
    article_text = models.TextField('article body')
    pub_date = models.DateTimeField('publishing date')
    area = models.ForeignKey(Area, on_delete=models.CASCADE)

    def __str__(self):
        return self.article_title

    def was_published_recently(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days=7))

    #class Meta:
    #    verbouse_name = 'Статья'
    #    verbouse_name_plural = 'Статьи'

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField('author name', max_length=50)
    comment_text = models.CharField('comment text', max_length=200)

    def __str__(self):
        return self.author_name

    #class Meta:
    #    verbouse_name = 'Комментарий'
    #    verbouse_name_plural = 'Комментарии'

cinemahistory/apps/articles/views.py
from django.shortcuts import render
from .models import Area, Article, Comment
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse


def index(request):
    #articles_list = Article.objects.all()
    #return render(request, 'articles/list.html', {'articles_list': articles_list})
    if 'search' in request.GET:
        return search(request)
    return render(request, 'pages/index.html')

def detail(request, article_id):
    if 'search' in request.GET:
        return search(request)
    try:
        a = Article.objects.get(id = article_id)
    except:
        raise Http404("Статья не найдена!")
    return render(request, 'pages/detail.html', {'article': a})

def area(request, area_name):
    if 'search' in request.GET:
        return search(request)
    try:
        a = Area.objects.get(area_name = area_name)
    except:
        raise Http404("Статья не найдена!")
    articles_list = a.article_set.all()

    return render(request, 'pages/area.html', {'area': a, 'articles_list': articles_list})

def search(request):
    a = Article.objects.filter(article_title__contains=request.GET['search'])
    return render(request, 'pages/search_results.html', {'articles_list': a, 'query': request.GET['search']})

cinemahistory/templates/_base.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <title>{% block title %} Сайт {% endblock %}</title>
</head>
<body>
  {% block content %}{% endblock %}
</body>
</html>

cinemahistory/templates/base.html
<!DOCTYPE HTML>
{% load static %}
{% load fill_temp %}
<html>
<!-- Mirrored from bluestnight.com/ by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 22 Dec 2019 13:23:39 GMT -->
<!-- Added by HTTrack -->
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
<!-- /Added by HTTrack -->

<head>
  <meta charset=utf-8>
  <meta name=viewport content="width=device-width,initial-scale=1">
  <title>{% block title %} Кинематограф XX {% endblock %}</title>
  <meta name=description itemprop=description content="BluestNight provides a growing bundle of web-related software designed to let you build your web presence your way. Every product is designed to be able to be customized to fit your needs and your tastes, while providing sane defaults. Each product comes with its own extensive documentation, as well as approachable guides to get you started. Best of all, they&amp;rsquo;re all open source! Midnight is a theme for the Hugo static site generator, featuring a configurable color scheme, integrated privacy policies through Iubenda1, optimizations for HTTP/2, and a well-documented plugin system to integrate your own code into the theme."
  id=desc>
  <meta name=generator content="Hugo 0.48">
  <link rel=alternate type=application/rss+xml title="BluestNight Feed" href=index.xml>
  <link rel=canonical href=index.html>
  <meta name=thumbnail content=images/thumbnail.svg>
  <link rel=dns-prefetch href=https://use.fontawesome.com/>
  <link rel=preconnect href=https://use.fontawesome.com/>
  <link rel=stylesheet href=https://use.fontawesome.com/releases/v5.2.0/css/all.css>
  <link rel=stylesheet href={% static "/css/foundation.min.f35916ba2f2723593ceb7babb94adc296f057cbc814b27b7672967944680f7e9.css" %}>
  <link rel=stylesheet href={% static "/css/dark.min.a2e0a27b84f040c06c153f1811086f6c2703f82371f3533c5ebb5617ad55f808.css" %}>
  <link rel=stylesheet href={% static "/css/styles.css" %}>
  <link rel=stylesheet href={% static "/css/reset.min.58d4832e34c59f168248179e8f6a0495f3f1ed2cb432fa09597f17f8d2916f62.css" %}>
  <link rel=stylesheet href={% static "/css/fonts.min.4ffd55649e797a49b8a6d3f70cdd1c97f25a942848a291346dd055c59bd4f010.css" %}>
  <link rel=stylesheet href={% static "/css/classes.min.717d03fc567fccb77be4ab35d1ac133e64e2cc160d72af4bf64a7ec26281238d.css" %}>
  <link rel=stylesheet href={% static "/css/pagination.min.a31cab125b1746c12a627603ca87c56d9bac853050a3b9e35f9616eafb8123f3.css" %}>
  <link rel=stylesheet href={% static "/css/page.min.9c0736cd7c3619c5dc37e1ae595a110df2e758a0932ecf237eb643c20d534553.css" %}>
  <link rel=stylesheet href={% static "/css/widgets.min.f86a3fac609b70f8c8746e1a9bf0ee6d7030716a21281e29e0010bd19b4f22d0.css" %}>
  <link rel=stylesheet href={% static "/css/list.min.98c794b9463ca90b39ad9aa66fd65a2e60ffb9c822b873df28bf5f0389bf2b73.css" %}>
  <link rel=stylesheet href={% static "/css/iubenda.min.59cd11b3165d3a316051def6255edaf053f93987605587c60274ab73b3de9ae8.css" %}>
  <link rel=preload media=print href={% static "/css/print.min.2e0961e511885e38a09cc9a9ff3de5ce7d7d2186bb9ed98a61f176688d4ef61a.css" %} as=style>
  <meta name=flattr:id content=ljq27k>
  <link rel=dns-prefetch href=https://cdnjs.cloudflare.com/>
  <link rel=preconnect href=https://cdnjs.cloudflare.com/>
  <link rel=preload href=index.json as=fetch>
  <link rel=stylesheet href={% static "/css/widgets/search.min.ed22f06ef5def38f6b47df5922d8c6ff133a4aedb6979e8d6582ddacac631c55.css" %}>
  <script src={% static "/js/relpreload.min.664f6d2b747d802a76801d4948aa59ce5c7dcb25c5e245c813c42a2346efb867.js" %}></script>
  <script src={% static "/js/loadCSS.min.59e75355ae9e2ed5d5371479f1b4f49f334679d04aa71bdb93559e580c5f7908.js" %}></script>
  <script src={% static "/js/asyncCSS.min.7325ff37331cd315b59a7af77205796df19e34822459cdaf7cbace135c836d82.js" %}></script>
  <link rel=apple-touch-icon sizes=180x180 href=apple-touch-icon.png>
  <link rel=icon type=image/png sizes=16x16 href=favicon-16x16df2b.png?nocache>
  <link rel=icon type=image/png sizes=32x32 href=favicon-32x32df2b.png?nocache>
  <link rel=icon href=favicondf2b.ico?nocache>
  <link rel=mask-icon href=safari-pinned-tab.svg color=#2073c9>
  <link rel=manifest href=site.webmanifest>
  <meta name=theme-color content=#2073c9>
  <meta name=apple-mobile-web-app-title content=BluestNight>
  <meta name=application-name content=BluestNight>
</head>

<body itemscope itemtype=http://schema.org/WebPage>
  <div class=off-canvas-wrapper>
    <button id=off-canvas-toggle type=button class="button hide-for-medium" aria-label="Open Menu" data-toggle=main-nav-off-canvas>
      <span class="fas fa-bars"></span></button>
      <div class="off-canvas position-left" id=main-nav-off-canvas data-off-canvas>
        <nav>
          <ul class="vertical menu drilldown" data-drilldown>
            {% for a in areas %}
              <li itemscope itemtype=http://schema.org/SiteNavigationElement><a class="main-nav button" tabindex=0 href="{% url 'articles:area' a.area_name %}">{{a.area_name_ru}}</a></li>
            {% endfor %}
          </ul>
        </nav>
      </div>
    <div id=site-container class="grid-container full off-canvas-content">
      <div class="grid-x full grid-container data-off-canvas-content">
        <div id=site-header class=cell>
          <a href={% url 'articles:index' %}>
            <header class="small-text-left medium-text-left grid-x"><img id=site-thumbnail class="cell shrink" src={% static "/images/thumbnail.png" %} data-width=93>
              <div id=site-title-container class="cell shrink grid-y">
                <div id=site-title class="cell shrink" itemprop=name>КИНЕМАТОГРАФ XX</div>
                <div class="cell shrink" id=site-tagline>Краткий обзор значимых кинематографистов XX века</div>
              </div>
            </header>
          </a>
          <nav id=main-nav class=small-hide>
            <ul class="dropdown menu" data-dropdown-menu>
              {% for a in areas %}
                <li itemscope itemtype=http://schema.org/SiteNavigationElement><a class="main-nav button" tabindex=0 href="{% url 'articles:area' a.area_name %}">{{a.area_name_ru}}</a></li>
              {% endfor %}
            </ul>
          </nav>
        </div>
        <div id=main-container class="cell grid-x grid-padding-x grid-container" role=main itemprop=mainContentOfPage>

          <main id=post-list class="cell medium-8">
            {% autoescape off %}
            {% block content %}{% endblock %}
            {% endautoescape %}
          </main>
          <aside class="cell small-12 small-order-2 medium-4" itemscope itemtype=http://schema.org/WPSideBar>
            <div class=widget>

              <div id=monero-sidebar-box class="grid-x hide">
                <input id=monero-wallet-address value=44M7tstc9TA4VAGTbDvpQ2Hm8HebtWqwe84ee1SCoShibucBNRWye7CBjmQnhNacJdB7kuSdK2eevbyZRd5fQ2z93jmbWC1 class="cell auto input-group-field" readonly>
                <div class="cell shrink input-group-button">
                  <button id=copy-monero-wallet class=button data-clipboard-target=#monero-wallet-address>
                    <span class="fas fa-copy"></span></button>
                </div>
              </div>
            </div>
            <div class=widget id=search-container>
              <header><span class=widget-header><span class="fas fa-search fa-xs" aria-hidden></span>Поиск</span>
              </header>
              <form>
                <input type=search name=search id=searchbox placeholder=Search... autocomplete=off>
              </form>
              <div id=search-results class="grid-y hide"></div>
            </div>
            <div class=widget>
              <header><span class=widget-header><span class="fas fa-pencil-alt fa-xs" aria-hidden></span>Последние посты</span>
              </header>
              <ul>
                {% for a in last_articles %}
                  <li><a href="{% url 'articles:detail' a.id %}">{{a.article_title}}</a></li>
                {% endfor %}
              </ul>
            </div>
            <div class=widget>
              <header><span class=widget-header><span class="fas fa-folder fa-xs" aria-hidden></span>Разное</span>
              </header>
              <ul>
                {% if other_articles %}
                {% for a in other_articles %}
                  <li><a href="{% url 'articles:detail' a.id %}">{{a.article_title}}</a></li>
                {% endfor %}
                {% endif %}
              </ul>
            </div>
            <script src={% static "js/iubenda.min.e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.js" %}></script>
    <script src=https://cdn.iubenda.com/iubenda.js defer async></script>
    <script src={% static "
          </aside>
        </div>
        <footer class="cell grid-x full align-middle">
          <div class="cell medium-4 small-text-center medium-text-left medium-left small-order-1 grid-x">
            <div class=cell><small>&copy; 2018
<span itemprop=publisher itemscope itemtype=http://schema.org/Organization><span itemprop=name>Michael Bryant.</span></span></small></div>
            <div class=cell><small>Built with <a href=https://gohugo.io/>Hugo</a> and <a href=products/midnight/index.html>Midnight</a>.</small></div>
          </div>
          <div class="cell medium-4 small-text-center medium-text-center small-order-2 grid-x">
            <div class="cell small-full small-text-center grid-x">
              <div class="cell medium-auto"><a href=http://www.iubenda.com/privacy-policy/8219381 class="iubenda-embed no-brand iubenda-white" title="Privacy Policy">Privacy Policy</a>
                <a href=http://www.iubenda.com/privacy-policy/8219381/cookie-policy class="iubenda-embed no-brand iubenda-white" title="Cookie Policy">Cookie Policy</a></div>
            </div>
          </div>
          <div id=social-icons class="grid-x cell medium-4 small-text-center small-order-3 medium-text-right"><a href=https://gitlab.com/BluestNight/BluestNight class="cell shrink" rel="me nofollow" title=GitLab aria-title="Fork me on GitLab!"><span class="fa-stack fa-xs"><span class="fas fa-square fa-stack-2x"></span><span class="fab fa-gitlab fa-stack-1x fa-inverse"></span></span></a></div>
        </footer>
      </div>
    </div>
    <script src={% static "/js/iubenda.min.e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.js" %}></script>
    <script src=https://cdn.iubenda.com/iubenda.js defer async></script>
    <script src={% static "/js/jquery.slim.min.766486af7a81bc2f1866d9b533267e0b1b850777b2bcf55295f5e285631f81b3.js" %} defer ></script>
    <script src={% static "/js/foundation.min.fb3831ae6e67578c11b76aeb20714c78af6563641917b09680aec5956e012f7f.js" %} defer ></script>
    <script src={% static "/js/thumbnail.min.d00d332865d7ed24a840ea42f1d1751eb61fcc00dc23dd130367e272ccfc10e7.js" %} defer ></script>
    <script src={% static "/js/widgets/clipboard.min.7380537dbe37c039bf72de37aa10f732ca0712daf47483baee10016c2082d9d1.js" %} defer ></script>
    <script src={% static "/js/widgets/support-sidebar.min.a2a4f3246c17e22f38f63288a0c7ec833f990606b35b31cd81974c7baf0866f3.js" %} defer ></script>
    <script src=https://cdnjs.cloudflare.com/ajax/libs/lunr.js/2.1.3/lunr.min.js defer></script>
    <script src={% static "/js/widgets/search.min.d6a2d0bd5fd318e4ebee49b4ef2da140c9886fd9ab0ad4d2e9954b01e7b47cfd.js" %} defer ></script>
    <script src={% static "/js/index.min.e22883a04526785bb35feb658da4974c160999432286921d7df30235cc21e4f3.js" %} defer ></script>
  </div>
</body>
<!-- Mirrored from bluestnight.com/ by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 22 Dec 2019 13:24:19 GMT -->

</html>

cinemahistory/templates/pages/area.html
{% extends 'base.html' %}

{% block title %}История кинематографа{% endblock %}

{% block content %}
<h1>{{area.area_name_ru}}</h1>
{% if articles_list %}
  {% for a in articles_list %}
    <a class="widget-header-small button" href="{% url 'articles:detail' a.id %}"><span class="fas fa-xs" aria-hidden></span>{{a.article_title}}</a>
  {% endfor %}
{% endif %}

{% endblock %}

cinemahistory/templates/pages/detail.html
{% extends 'base.html' %}

{% block title %}{{article.article_title}}{% endblock %}

{% block content %}

  <h2>{{article.article_title}}</h2>
  <p>{{article.article_text}}</p>
  <hr>
  <em>{{article.pub_date}}</em>



{% endblock %}

cinemahistory/templates/pages/index.html
{% extends 'base.html' %}

{% block title %}История кинематографа{% endblock %}

{% block content %}

<p class="content_text">Первым описанием плоских движущихся изображений принято считать рассказ о тенях, «отбрасываемых огнем … на стену пещеры» в начале седьмой книги платоновского Государства. Описания, предвосхищающие кино, также иногда находят у Герона Александрийского и Клавдия Птолемея.</p>
<p class="content_text">Однако если говорить не о сходстве разного рода метафор со знакомым нам явлением, а о реальной системе, позволяющей записывать и воспроизводить бесконечное разнообразие движущихся плоских изображений, то непосредственными предшественниками кинематографа были, во-первых, различные игрушки с сериями картинок, которые при быстрой их смене воспринимались как одно движущееся изображение (среди таких игрушек надо отметить т.н. «чудо-блокнот», «зоотроп» и «фенакистоскоп») – все эти системы позволяли воспроизводить не более нескольких секунд движения. А во-вторых, предшественником кино как системы был волшебный фонарь (также laterna magica – нечто вроде современного диапроектора), который в середине 19 в. часто снабжался приспособлениями, позволяющими имитировать некоторые виды движения.</p>
<hr>
<p class="content_text">Но создание кинематографа как системы воспроизведения достаточно длительного движущегося изображения, причем изображения совершенно произвольного (в том числе и полностью жизнеподобного) оказалось возможным только после того, как возникла фотография, а чувствительность фотоматериалов стала позволять снимать при коротких выдержках. Когда – с изобретением в конце 1870-х бромсеребряных желатиновых эмульсий, являющихся основой фото- и кинопроцессов по сей день – это произошло, практически сразу же стали разрабатываться различные системы записи движения.</p>

{% endblock %}

cinemahistory/templates/pages/list.html
{% extends 'base.html' %}

{% block title %} эх статьи мои статьи {% endblock %}

{% block content %}

  {% if articles_list %}
    {% for a in articles_list %}
      <a href=" {% url 'articles:detail' a.id %} ">{{a.article_title}}</a>
    {% endfor %}
  {% endif %}

{% endblock %}

cinemahistory/templates/pages/search_results.html
{% extends 'base.html' %}

{% block title %}Поиск статьи{% endblock %}

{% block content %}
<p><strong>По запросу "{{query}}" найдены следующие статьи:</strong></p>
{% if articles_list %}
  {% for a in articles_list %}
    <a class="widget-header-small button" href="{% url 'articles:detail' a.id %}"><span class="fas fa-xs" aria-hidden></span>{{a.article_title}}</a>
  {% endfor %}
{% endif %}

{% endblock %}